# remote_theme: mmistakes/minimal-mistakes
theme: minima
classes: wide
title: "This is the project page for Multi-Decoder DPRNN" 
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
